export const FIELD_ID_BY_ERROR_PATH: Record<string, string> = {
  "personalData.firstName": "firstName",
  "personalData.lastName": "lastName",
  "personalData.documentNumber": "documentNumber",
  "personalData.birthDate": "birthDate-account-link",
  "personalData.phoneNumber": "phoneNumber",
  "personalData.email": "email",
  "academicBackground.currentlyStudying": "currentlyStudying",
  "academicBackground.educationLevel": "educationLevel",
  "academicBackground.schoolOrigin": "schoolOrigin",
  "academicBackground.levelCompleted": "levelCompleted",
  "academicBackground.secondaryCompleted": "secondaryCompleted",
  "healthInclusion.adjustmentDetails": "adjustmentDetails",
  "responsible.fullName": "responsibleFullName",
  "responsible.documentNumber": "responsibleDocumentNumber",
  "responsible.phoneNumber": "responsiblePhoneNumber",
  "responsible.email": "responsibleEmail",
  "responsible.occupation": "responsibleOccupation",
  "responsible.educationLevel": "responsibleEducationLevel",
  "preference.preferredShift": "preferredShift",
  "preference.previousTeacher": "previousTeacher",
};
