services:
  dev:
    container_name: boero-ui-dev
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - path: .env.dev
        required: false
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      CI: "true"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public
          target: /app/public
        - action: sync
          path: ./components.json
          target: /app/components.json
        - action: sync
          path: ./next.config.ts
          target: /app/next.config.ts
        - action: sync
          path: ./tsconfig.json
          target: /app/tsconfig.json
        - action: sync
          path: ./postcss.config.mjs
          target: /app/postcss.config.mjs
        - action: sync
          path: ./eslint.config.mjs
          target: /app/eslint.config.mjs
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./pnpm-lock.yaml
        - action: rebuild
          path: ./pnpm-workspace.yaml

