export const ACADEMIC_ENROLLMENT_STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  PENDING_RESULT: "PENDING_RESULT",
  REGULARIZED: "REGULARIZED",
  PROMOTED: "PROMOTED",
  PASSED: "PASSED",
  FAILED: "FAILED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
} as const;

export type AcademicEnrollmentStatus = (typeof ACADEMIC_ENROLLMENT_STATUS)[keyof typeof ACADEMIC_ENROLLMENT_STATUS];
