export const COURSE_ENROLLMENT_GRADE_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  PENDING_CHANGES: "PENDING_CHANGES",
  PENDING_DELETION: "PENDING_DELETION",
} as const;

export type CourseEnrollmentGradeStatus =
  (typeof COURSE_ENROLLMENT_GRADE_STATUS)[keyof typeof COURSE_ENROLLMENT_GRADE_STATUS];
