export const COURSE_ENROLLMENT_STATUS = {
  ENROLLED: "ENROLLED",
  COMPLETED: "COMPLETED",
  WITHDRAWN: "WITHDRAWN",
  ADMINISTRATIVELY_WITHDRAWN: "ADMINISTRATIVELY_WITHDRAWN",
} as const;

export type CourseEnrollmentStatus = (typeof COURSE_ENROLLMENT_STATUS)[keyof typeof COURSE_ENROLLMENT_STATUS];
