export const ENROLLMENT_DOCUMENT_TYPE = {
  DNI_FRONT: "DNI_FRONT",
  DNI_BACK: "DNI_BACK",
  SECONDARY_CERTIFICATE: "SECONDARY_CERTIFICATE",
  HEALTH_REPORT: "HEALTH_REPORT",
  PHOTO_ID: "PHOTO_ID",
} as const;

export type EnrollmentDocumentType = (typeof ENROLLMENT_DOCUMENT_TYPE)[keyof typeof ENROLLMENT_DOCUMENT_TYPE];
