export const ENROLLMENT_APPLICATION_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;

export type EnrollmentApplicationStatus = (typeof ENROLLMENT_APPLICATION_STATUS)[keyof typeof ENROLLMENT_APPLICATION_STATUS];
